package wollumetric;

import java.io.File;
import java.util.ArrayList;
import java.util.Random;

import processing.core.PApplet;
import processing.core.PGraphics;
import processing.core.PVector;
import processing.data.JSONObject;

public class Wollumetric extends ProcessingObject {
	public final static String RENDERER = "wollumetric.WGraphics";
	public PVector size;
	public PVector nearSize;
	public float vShiftAnchor = 0.5f;
	private WGraphics gfx;
	private float nearDepth;
	private float farDepth;
	private ArrayList<Line> lines;

	/**
	* <strong>Builds a new Wollumetric</strong>
	*
	* <p>Requires a JSON config file. Configurations are as follows:</p>
	*
	* <ul>
	*   <li>"wiremapFile" is the path (relative to the data folder) to a wiremap
	*       text file. Each line contains: angle x z height separated by
	*       whitespace. Generated by the Wollumetric py-scripts.</li>
	* </ul>
	*
	* <p>Optional settings:</p>
	* <ul>
	*   <li>"vShift" controls the vertical alignment of the projector frustum.
	*       "bot" = projector center at the bottom (projects up),
	*       "cen" = projector center at the middle (default),
	*       "top" = projector center at the top (projects down).</li>
	* </ul>
	*
	* <p>* Real units can be centimeters, inches, etc. Stay consistent.</p>
	*
	* <p>If you update the config or wiremap file, delete the cached map .png
	* from the data folder (or remove the "mapCache" key from the JSON) to
	* force regeneration.</p>
	*
	* @param  jsonPath  Name of the config file
	* @param  p         the applet (usually "this")
	*/
	public Wollumetric(String jsonPath, PApplet p) {
		Wollumetric.pApplet = p;

		/* renderer */
		bindToRenderer(p);
		gfx.sphereShader = gfx.loadShader(WGraphics.class.getResource("sphere.glsl").toString());
		gfx.boxShader = gfx.loadShader(WGraphics.class.getResource("box.glsl").toString());
		gfx.meshShader = gfx.loadShader(WGraphics.class.getResource("mesh.glsl").toString());

		/* config */
		JSONObject config = p.loadJSONObject(p.dataPath(jsonPath));
		String wiremapFile = config.getString("wiremapFile");
		String wiremapName = wiremapFile.replace(".txt", "");

		String[] params = wiremapName.split("_")[0].split("-");
		float maxX = Float.parseFloat(params[2].split("x")[0]);
		float maxZ = Float.parseFloat(params[2].split("x")[1]);
		float throwRatio = Float.parseFloat(params[3]);

		/* vertical shift: "bot", "cen" (default), or "top" */
		String vShift = config.getString("vShift", "cen");
		if (vShift.equals("bot")) vShiftAnchor = 0.0f;
		else if (vShift.equals("top")) vShiftAnchor = 1.0f;
		else vShiftAnchor = 0.5f;

		/* derived geometry */
		nearDepth = throwRatio * maxX;
		farDepth = nearDepth + maxZ;
		float nearY = maxX * ((float) p.height / (float) p.width);
		nearSize = new PVector(maxX, nearY, maxZ);
		/* size covers the full projector frustum (far-plane extents) */
		float farX = maxX * farDepth / nearDepth;
		float farY = farX * ((float) p.height / (float) p.width);
		size = new PVector(farX, farY, maxZ);

		/* load wiremap — each line: angle x z [height] */
		String[] wiremapLines = p.loadStrings(p.dataPath(wiremapFile));
		int numberOfLines = wiremapLines.length;
		int pxPerSlice = p.width / numberOfLines;
		Line.setSliceWidth(pxPerSlice);

		/* build lines */
		lines = new ArrayList<Line>();
		for (int i = 0; i < numberOfLines; i++) {
			String[] parts = wiremapLines[i].trim().split("\\s+");
			float x = Float.parseFloat(parts[1]);
			float z = Float.parseFloat(parts[2]);
			float y = Float.parseFloat(parts[3]);

			float lineX = x + (size.x / 2.0f);
			float lineZ = z;
			float lineY = y;
			float sliceXOffset = pxPerSlice * i;

			lines.add(new Line(lineX, lineZ, sliceXOffset, lineY, this));
		}

		/* load calibration if available */
		String calibFile;
		if (wiremapFile.endsWith("_strings.txt")) {
			calibFile = wiremapFile.substring(0, wiremapFile.length() - "_strings.txt".length()) + "_calib.txt";
		} else {
			calibFile = wiremapFile + "_calib.txt";
		}
		String calibHash = vShift;
		File calibFileObj = new File(p.dataPath(calibFile));
		if (calibFileObj.exists()) {
			String[] calibLines = p.loadStrings(p.dataPath(calibFile));
			int hash = 0;
			for (int i = 0; i < Math.min(calibLines.length, lines.size()); i++) {
				String[] cparts = calibLines[i].trim().split("\\s+");
				if (cparts.length >= 2) {
					int cw = Integer.parseInt(cparts[0]);
					int co = Integer.parseInt(cparts[1]);
					lines.get(i).setCalibration(cw, co);
					hash = hash * 31 + cw;
					hash = hash * 31 + co;
				}
			}
			calibHash = vShift + "_" + Integer.toHexString(hash);
		}

		/* find or build map */
		boolean generateNewMap = false;
		String storedCalibHash = config.getString("calibCache", "");
		 if (!calibHash.equals(storedCalibHash)) {
			generateNewMap = true;
		} else {
			File f = new File(p.dataPath(wiremapName + ".png"));
			if (!f.exists()) {
				generateNewMap = true;
			}
		}

		if (generateNewMap) {
			config.setString("calibCache", calibHash);
			p.saveJSONObject(config, p.dataPath(jsonPath));
			PGraphics mapBuffer = p.createGraphics(p.width, p.height);
			mapBuffer.beginDraw();
			mapBuffer.noSmooth();
			for (int i = 0; i < lines.size(); i++) {
				lines.get(i).renderMap(mapBuffer);
			}
			mapBuffer.endDraw();
			mapBuffer.save(p.dataPath(wiremapName + ".png"));
		}

		gfx.mapData = p.loadImage(p.dataPath(wiremapName + ".png"));
	}

	public WGraphics getGfx() {
		return gfx;
	}

	public Line getLine(int index) {
		return lines.get(index);
	}

	public int getLineCount() {
		return lines.size();
	}

	private void bindToRenderer(PApplet p) {
		gfx = (WGraphics) p.g;
		gfx.wollumetric = this;
	}
}