package wollumetric;

import java.io.File;
import java.util.ArrayList;
import java.util.Random;

import processing.core.PApplet;
import processing.core.PGraphics;
import processing.core.PVector;
import processing.data.JSONObject;

public class Wollumetric extends ProcessingObject {
	public final static String RENDERER = "wollumetric.WGraphics";
	public PVector size;
	private WGraphics gfx;
	private float nearDepth;
	private float farDepth;
	private ArrayList<Line> lines;

	/**
	* <strong>Builds a new Wollumetric</strong>
	*
	* <p>Requires a JSON config file. Configurations are as follows:</p>
	*
	* <ul>
	*   <li>"wiremapFile" is the path (relative to the data folder) to a wiremap
	*       text file. Each line contains: angle x z height separated by
	*       whitespace. Generated by the Wollumetric py-scripts.</li>
	*   <li>"structureWidth" is the physical width of the display at the near
	*       plane, in real units*.</li>
	*   <li>"structureDepth" is the physical depth of the display, in real
	*       units*.</li>
	*   <li>"throwRatio" is the projector's throw ratio
	*       (projection distance / image width).</li>
	*   <li>"margin" is the number of black pixels between each column of pixels.
	*       Defaults to 0 if omitted.</li>
	*   <li>"mapCache" is used internally for map caching.</li>
	* </ul>
	*
	* <p>* Real units can be centimeters, inches, etc. Stay consistent.</p>
	*
	* <p>If you update the config or wiremap file, delete the cached map .png
	* from the data folder (or remove the "mapCache" key from the JSON) to
	* force regeneration.</p>
	*
	* @param  jsonPath  Name of the config file
	* @param  p         the applet (usually "this")
	*/
	public Wollumetric(String jsonPath, PApplet p) {
		Wollumetric.pApplet = p;

		/* renderer */
		bindToRenderer(p);
		gfx.sphereShader = gfx.loadShader(WGraphics.class.getResource("sphere.glsl").toString());
		gfx.boxShader = gfx.loadShader(WGraphics.class.getResource("box.glsl").toString());

		/* config */
		JSONObject config = p.loadJSONObject(p.dataPath(jsonPath));
		float maxX = config.getFloat("structureWidth");
		float maxZ = config.getFloat("structureDepth");
		float throwRatio = config.getFloat("throwRatio");
		int margin = config.getInt("margin", 0);
		String wiremapFile = config.getString("wiremapFile");

		/* derived geometry */
		nearDepth = throwRatio * maxX;
		farDepth = nearDepth + maxZ;
		float maxY = maxX * ((float) p.height / (float) p.width);
		size = new PVector(maxX, maxY, maxZ);

		/* load wiremap — each line: angle x z [height] */
		String[] wiremapLines = p.loadStrings(p.dataPath(wiremapFile));
		int numberOfLines = wiremapLines.length;
		int pxPerSlice = p.width / numberOfLines;
		Line.setSliceWidth(pxPerSlice - margin);

		/* build lines */
		lines = new ArrayList<Line>();
		for (int i = 0; i < numberOfLines; i++) {
			String[] parts = wiremapLines[i].trim().split("\\s+");
			float x = Float.parseFloat(parts[1]);
			float z = Float.parseFloat(parts[2]);
			float y = Float.parseFloat(parts[3]);

			float lineX = x + (size.x / 2.0f);
			float lineZ = z;
			float lineY = y;
			float sliceXOffset = pxPerSlice * i + (margin / 2);

			lines.add(new Line(lineX, lineZ, sliceXOffset, lineY, this));
		}

		/* find or build map */
		boolean generateNewMap = false;
		String mapKey = config.getString("mapCache", "undefined");
		if (mapKey.equals("undefined")) {
			generateNewMap = true;
		} else {
			File f = new File(p.dataPath(mapKey + ".png"));
			if (!f.exists()) {
				generateNewMap = true;
			}
		}

		if (generateNewMap) {
			Random r = new Random();
			StringBuffer sb = new StringBuffer();
			while (sb.length() < 16) {
				sb.append(Integer.toHexString(r.nextInt()));
			}
			mapKey = sb.toString().substring(0, 15);
			config.setString("mapCache", mapKey);
			p.saveJSONObject(config, p.dataPath(jsonPath));
			PGraphics mapBuffer = p.createGraphics(p.width, p.height);
			mapBuffer.beginDraw();
			mapBuffer.noSmooth();
			for (int i = 0; i < lines.size(); i++) {
				lines.get(i).renderMap(mapBuffer);
			}
			mapBuffer.endDraw();
			mapBuffer.save(p.dataPath(mapKey + ".png"));
		}

		gfx.mapData = p.loadImage(p.dataPath(mapKey + ".png"));
	}

	public WGraphics getGfx() {
		return gfx;
	}

	public Line getLine(int index) {
		return lines.get(index);
	}

	public int getLineCount() {
		return lines.size();
	}

	private void bindToRenderer(PApplet p) {
		gfx = (WGraphics) p.g;
		gfx.wollumetric = this;
	}
}